@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title after command "addtask n/task1 ..."

package States {
    class ABState1 as "<u>ab0:AddressBook</u>"
    class ABState2 as "<u>ab1:AddressBook</u>"
    class TLState1 as "<u>tl0:TaskList</u>"
    class TLState2 as "<u>tl1:TaskList</u>"
}
ABState1 -[hidden]right-> ABState2
ABState2 -[hidden]right-> TLState1
TLState1 -[hidden]right-> TLState2
hide ABState2

class Pointer as "Address Book State" #FFFFFF
class Pointer2 as "Task List State" #FFFFFF
Pointer -up-> ABState1
Pointer2 -up-> TLState2
@end
